name: api-default-dev
services:
  app:
    build: .
    container_name: php-app
    restart: always
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    volumes:
      - ./../../app:/var/www/html/
      - ./../../store:/var/www/store/
    depends_on:
      - db

  db:
    image: mariadb:12.0.2
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ:  ${MYSQL_TZ}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  email-worker-redis:
    build: .
    container_name: email-worker-redis
    restart: always
    volumes:
      - ./../../app:/var/www/html
      - ./../../store:/var/www/store/
    working_dir: /var/www/html
    depends_on:
      - redis
    command: php /var/www/html/bin/RunWorkerEmail.php

volumes:
  dbdata:
